name: PHP Plugin Release

on:
  push:
    branches: [ "fix/fix-release.yaml" ]
  pull_request:
    branches: [ "fix/fix-release.yaml" ]

permissions:
  contents: read

jobs:
   release:
    name: "Release"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: ./upload/system/library/vpg
      run: composer install --prefer-dist --no-progress && ${{ secrets.GITHUB_TOKEN }}
      
    - name: Zipping plugin
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r vodapay-gatewat.ocmod.zip upload

    - name: create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
